#include <php.h>

#ifndef LIBPHPCASSANDRA_EXT_SRC_FUTURES_FUTURESESSION_FUTURESESSION_H_
#define LIBPHPCASSANDRA_EXT_SRC_FUTURES_FUTURESESSION_FUTURESESSION_H_

void php_driver_define_FutureSession(zend_class_entry* future_interface);

#endif
