#include <zend_types.h>

#ifndef LIBPHPCASSANDRA_EXT_SRC_RETRYPOLICY_DEFAULTPOLICY_DEFAULTPOLICY_H_
#define LIBPHPCASSANDRA_EXT_SRC_RETRYPOLICY_DEFAULTPOLICY_DEFAULTPOLICY_H_

void PhpDriverDefineRetryPolicyDefault(zend_class_entry* retryPolicyInterface);

#endif // LIBPHPCASSANDRA_EXT_SRC_RETRYPOLICY_DEFAULTPOLICY_DEFAULTPOLICY_H_
