#include <zend_types.h>

#ifndef LIBPHPCASSANDRA_EXT_SRC_RETRYPOLICY_FALLTHROUGH_FALLTHROUGH_H_
#define LIBPHPCASSANDRA_EXT_SRC_RETRYPOLICY_FALLTHROUGH_FALLTHROUGH_H_

void PhpDriverDefineRetryPolicyFallthrough(zend_class_entry* retryPolicyInterface);

#endif // LIBPHPCASSANDRA_EXT_SRC_RETRYPOLICY_FALLTHROUGH_FALLTHROUGH_H_
