/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 0d89982928614921a6324b84276c539dfdaa152b */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_Cassandra_DefaultMaterializedView_name, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_Cassandra_DefaultMaterializedView_option, 0, 1, IS_MIXED, 0)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_Cassandra_DefaultMaterializedView_options, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_class_Cassandra_DefaultMaterializedView_comment, 0, 0, MAY_BE_STRING|MAY_BE_FALSE)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_class_Cassandra_DefaultMaterializedView_readRepairChance, 0, 0, MAY_BE_DOUBLE|MAY_BE_FALSE)
ZEND_END_ARG_INFO()

#define arginfo_class_Cassandra_DefaultMaterializedView_localReadRepairChance arginfo_class_Cassandra_DefaultMaterializedView_readRepairChance

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_class_Cassandra_DefaultMaterializedView_gcGraceSeconds, 0, 0, MAY_BE_LONG|MAY_BE_FALSE)
ZEND_END_ARG_INFO()

#define arginfo_class_Cassandra_DefaultMaterializedView_caching arginfo_class_Cassandra_DefaultMaterializedView_comment

#define arginfo_class_Cassandra_DefaultMaterializedView_bloomFilterFPChance arginfo_class_Cassandra_DefaultMaterializedView_readRepairChance

#define arginfo_class_Cassandra_DefaultMaterializedView_memtableFlushPeriodMs arginfo_class_Cassandra_DefaultMaterializedView_gcGraceSeconds

#define arginfo_class_Cassandra_DefaultMaterializedView_defaultTTL arginfo_class_Cassandra_DefaultMaterializedView_gcGraceSeconds

#define arginfo_class_Cassandra_DefaultMaterializedView_speculativeRetry arginfo_class_Cassandra_DefaultMaterializedView_comment

#define arginfo_class_Cassandra_DefaultMaterializedView_indexInterval arginfo_class_Cassandra_DefaultMaterializedView_gcGraceSeconds

#define arginfo_class_Cassandra_DefaultMaterializedView_compactionStrategyClassName arginfo_class_Cassandra_DefaultMaterializedView_comment

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_class_Cassandra_DefaultMaterializedView_compactionStrategyOptions, 0, 0, MAY_BE_ARRAY|MAY_BE_FALSE)
ZEND_END_ARG_INFO()

#define arginfo_class_Cassandra_DefaultMaterializedView_compressionParameters arginfo_class_Cassandra_DefaultMaterializedView_compactionStrategyOptions

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_class_Cassandra_DefaultMaterializedView_populateIOCacheOnFlush, 0, 0, MAY_BE_BOOL|MAY_BE_FALSE)
ZEND_END_ARG_INFO()

#define arginfo_class_Cassandra_DefaultMaterializedView_replicateOnWrite arginfo_class_Cassandra_DefaultMaterializedView_populateIOCacheOnFlush

#define arginfo_class_Cassandra_DefaultMaterializedView_maxIndexInterval arginfo_class_Cassandra_DefaultMaterializedView_gcGraceSeconds

#define arginfo_class_Cassandra_DefaultMaterializedView_minIndexInterval arginfo_class_Cassandra_DefaultMaterializedView_gcGraceSeconds

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_TYPE_MASK_EX(arginfo_class_Cassandra_DefaultMaterializedView_column, 0, 1, Cassandra\\Column, MAY_BE_FALSE)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_Cassandra_DefaultMaterializedView_columns arginfo_class_Cassandra_DefaultMaterializedView_options

#define arginfo_class_Cassandra_DefaultMaterializedView_partitionKey arginfo_class_Cassandra_DefaultMaterializedView_options

#define arginfo_class_Cassandra_DefaultMaterializedView_primaryKey arginfo_class_Cassandra_DefaultMaterializedView_options

#define arginfo_class_Cassandra_DefaultMaterializedView_clusteringKey arginfo_class_Cassandra_DefaultMaterializedView_options

#define arginfo_class_Cassandra_DefaultMaterializedView_clusteringOrder arginfo_class_Cassandra_DefaultMaterializedView_options

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_Cassandra_DefaultMaterializedView_baseTable, 0, 0, Cassandra\\Table, 1)
ZEND_END_ARG_INFO()


ZEND_METHOD(Cassandra_DefaultMaterializedView, name);
ZEND_METHOD(Cassandra_DefaultMaterializedView, option);
ZEND_METHOD(Cassandra_DefaultMaterializedView, options);
ZEND_METHOD(Cassandra_DefaultMaterializedView, comment);
ZEND_METHOD(Cassandra_DefaultMaterializedView, readRepairChance);
ZEND_METHOD(Cassandra_DefaultMaterializedView, localReadRepairChance);
ZEND_METHOD(Cassandra_DefaultMaterializedView, gcGraceSeconds);
ZEND_METHOD(Cassandra_DefaultMaterializedView, caching);
ZEND_METHOD(Cassandra_DefaultMaterializedView, bloomFilterFPChance);
ZEND_METHOD(Cassandra_DefaultMaterializedView, memtableFlushPeriodMs);
ZEND_METHOD(Cassandra_DefaultMaterializedView, defaultTTL);
ZEND_METHOD(Cassandra_DefaultMaterializedView, speculativeRetry);
ZEND_METHOD(Cassandra_DefaultMaterializedView, indexInterval);
ZEND_METHOD(Cassandra_DefaultMaterializedView, compactionStrategyClassName);
ZEND_METHOD(Cassandra_DefaultMaterializedView, compactionStrategyOptions);
ZEND_METHOD(Cassandra_DefaultMaterializedView, compressionParameters);
ZEND_METHOD(Cassandra_DefaultMaterializedView, populateIOCacheOnFlush);
ZEND_METHOD(Cassandra_DefaultMaterializedView, replicateOnWrite);
ZEND_METHOD(Cassandra_DefaultMaterializedView, maxIndexInterval);
ZEND_METHOD(Cassandra_DefaultMaterializedView, minIndexInterval);
ZEND_METHOD(Cassandra_DefaultMaterializedView, column);
ZEND_METHOD(Cassandra_DefaultMaterializedView, columns);
ZEND_METHOD(Cassandra_DefaultMaterializedView, partitionKey);
ZEND_METHOD(Cassandra_DefaultMaterializedView, primaryKey);
ZEND_METHOD(Cassandra_DefaultMaterializedView, clusteringKey);
ZEND_METHOD(Cassandra_DefaultMaterializedView, clusteringOrder);
ZEND_METHOD(Cassandra_DefaultMaterializedView, baseTable);


static const zend_function_entry class_Cassandra_DefaultMaterializedView_methods[] = {
	ZEND_ME(Cassandra_DefaultMaterializedView, name, arginfo_class_Cassandra_DefaultMaterializedView_name, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, option, arginfo_class_Cassandra_DefaultMaterializedView_option, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, options, arginfo_class_Cassandra_DefaultMaterializedView_options, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, comment, arginfo_class_Cassandra_DefaultMaterializedView_comment, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, readRepairChance, arginfo_class_Cassandra_DefaultMaterializedView_readRepairChance, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, localReadRepairChance, arginfo_class_Cassandra_DefaultMaterializedView_localReadRepairChance, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, gcGraceSeconds, arginfo_class_Cassandra_DefaultMaterializedView_gcGraceSeconds, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, caching, arginfo_class_Cassandra_DefaultMaterializedView_caching, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, bloomFilterFPChance, arginfo_class_Cassandra_DefaultMaterializedView_bloomFilterFPChance, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, memtableFlushPeriodMs, arginfo_class_Cassandra_DefaultMaterializedView_memtableFlushPeriodMs, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, defaultTTL, arginfo_class_Cassandra_DefaultMaterializedView_defaultTTL, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, speculativeRetry, arginfo_class_Cassandra_DefaultMaterializedView_speculativeRetry, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, indexInterval, arginfo_class_Cassandra_DefaultMaterializedView_indexInterval, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, compactionStrategyClassName, arginfo_class_Cassandra_DefaultMaterializedView_compactionStrategyClassName, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, compactionStrategyOptions, arginfo_class_Cassandra_DefaultMaterializedView_compactionStrategyOptions, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, compressionParameters, arginfo_class_Cassandra_DefaultMaterializedView_compressionParameters, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, populateIOCacheOnFlush, arginfo_class_Cassandra_DefaultMaterializedView_populateIOCacheOnFlush, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, replicateOnWrite, arginfo_class_Cassandra_DefaultMaterializedView_replicateOnWrite, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, maxIndexInterval, arginfo_class_Cassandra_DefaultMaterializedView_maxIndexInterval, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, minIndexInterval, arginfo_class_Cassandra_DefaultMaterializedView_minIndexInterval, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, column, arginfo_class_Cassandra_DefaultMaterializedView_column, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, columns, arginfo_class_Cassandra_DefaultMaterializedView_columns, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, partitionKey, arginfo_class_Cassandra_DefaultMaterializedView_partitionKey, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, primaryKey, arginfo_class_Cassandra_DefaultMaterializedView_primaryKey, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, clusteringKey, arginfo_class_Cassandra_DefaultMaterializedView_clusteringKey, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, clusteringOrder, arginfo_class_Cassandra_DefaultMaterializedView_clusteringOrder, ZEND_ACC_PUBLIC)
	ZEND_ME(Cassandra_DefaultMaterializedView, baseTable, arginfo_class_Cassandra_DefaultMaterializedView_baseTable, ZEND_ACC_PUBLIC)
	ZEND_FE_END
};

static zend_class_entry *register_class_Cassandra_DefaultMaterializedView(zend_class_entry *class_entry_Cassandra_MaterializedView)
{
	zend_class_entry ce, *class_entry;

	INIT_NS_CLASS_ENTRY(ce, "Cassandra", "DefaultMaterializedView", class_Cassandra_DefaultMaterializedView_methods);
	class_entry = zend_register_internal_class_ex(&ce, class_entry_Cassandra_MaterializedView);
	class_entry->ce_flags |= ZEND_ACC_FINAL|ZEND_ACC_NO_DYNAMIC_PROPERTIES;

	return class_entry;
}
