/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 744308143ef60ae2b59290004f61b2da67be4d54 */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_Cassandra_Table_name, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_Cassandra_Table_option, 0, 1, IS_MIXED, 0)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_Cassandra_Table_options, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_class_Cassandra_Table_comment, 0, 0, MAY_BE_STRING|MAY_BE_FALSE)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_class_Cassandra_Table_readRepairChance, 0, 0, MAY_BE_DOUBLE|MAY_BE_FALSE)
ZEND_END_ARG_INFO()

#define arginfo_class_Cassandra_Table_localReadRepairChance arginfo_class_Cassandra_Table_readRepairChance

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_class_Cassandra_Table_gcGraceSeconds, 0, 0, MAY_BE_LONG|MAY_BE_FALSE)
ZEND_END_ARG_INFO()

#define arginfo_class_Cassandra_Table_caching arginfo_class_Cassandra_Table_comment

#define arginfo_class_Cassandra_Table_bloomFilterFPChance arginfo_class_Cassandra_Table_readRepairChance

#define arginfo_class_Cassandra_Table_memtableFlushPeriodMs arginfo_class_Cassandra_Table_gcGraceSeconds

#define arginfo_class_Cassandra_Table_defaultTTL arginfo_class_Cassandra_Table_gcGraceSeconds

#define arginfo_class_Cassandra_Table_speculativeRetry arginfo_class_Cassandra_Table_comment

#define arginfo_class_Cassandra_Table_indexInterval arginfo_class_Cassandra_Table_gcGraceSeconds

#define arginfo_class_Cassandra_Table_compactionStrategyClassName arginfo_class_Cassandra_Table_comment

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_class_Cassandra_Table_compactionStrategyOptions, 0, 0, MAY_BE_ARRAY|MAY_BE_FALSE)
ZEND_END_ARG_INFO()

#define arginfo_class_Cassandra_Table_compressionParameters arginfo_class_Cassandra_Table_compactionStrategyOptions

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_class_Cassandra_Table_populateIOCacheOnFlush, 0, 0, MAY_BE_BOOL|MAY_BE_FALSE)
ZEND_END_ARG_INFO()

#define arginfo_class_Cassandra_Table_replicateOnWrite arginfo_class_Cassandra_Table_populateIOCacheOnFlush

#define arginfo_class_Cassandra_Table_maxIndexInterval arginfo_class_Cassandra_Table_gcGraceSeconds

#define arginfo_class_Cassandra_Table_minIndexInterval arginfo_class_Cassandra_Table_gcGraceSeconds

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_TYPE_MASK_EX(arginfo_class_Cassandra_Table_column, 0, 1, Cassandra\\Column, MAY_BE_FALSE)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_Cassandra_Table_columns arginfo_class_Cassandra_Table_options

#define arginfo_class_Cassandra_Table_partitionKey arginfo_class_Cassandra_Table_options

#define arginfo_class_Cassandra_Table_primaryKey arginfo_class_Cassandra_Table_options

#define arginfo_class_Cassandra_Table_clusteringKey arginfo_class_Cassandra_Table_options

#define arginfo_class_Cassandra_Table_clusteringOrder arginfo_class_Cassandra_Table_options




static const zend_function_entry class_Cassandra_Table_methods[] = {
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, name, arginfo_class_Cassandra_Table_name, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, option, arginfo_class_Cassandra_Table_option, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, options, arginfo_class_Cassandra_Table_options, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, comment, arginfo_class_Cassandra_Table_comment, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, readRepairChance, arginfo_class_Cassandra_Table_readRepairChance, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, localReadRepairChance, arginfo_class_Cassandra_Table_localReadRepairChance, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, gcGraceSeconds, arginfo_class_Cassandra_Table_gcGraceSeconds, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, caching, arginfo_class_Cassandra_Table_caching, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, bloomFilterFPChance, arginfo_class_Cassandra_Table_bloomFilterFPChance, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, memtableFlushPeriodMs, arginfo_class_Cassandra_Table_memtableFlushPeriodMs, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, defaultTTL, arginfo_class_Cassandra_Table_defaultTTL, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, speculativeRetry, arginfo_class_Cassandra_Table_speculativeRetry, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, indexInterval, arginfo_class_Cassandra_Table_indexInterval, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, compactionStrategyClassName, arginfo_class_Cassandra_Table_compactionStrategyClassName, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, compactionStrategyOptions, arginfo_class_Cassandra_Table_compactionStrategyOptions, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, compressionParameters, arginfo_class_Cassandra_Table_compressionParameters, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, populateIOCacheOnFlush, arginfo_class_Cassandra_Table_populateIOCacheOnFlush, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, replicateOnWrite, arginfo_class_Cassandra_Table_replicateOnWrite, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, maxIndexInterval, arginfo_class_Cassandra_Table_maxIndexInterval, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, minIndexInterval, arginfo_class_Cassandra_Table_minIndexInterval, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, column, arginfo_class_Cassandra_Table_column, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, columns, arginfo_class_Cassandra_Table_columns, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, partitionKey, arginfo_class_Cassandra_Table_partitionKey, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, primaryKey, arginfo_class_Cassandra_Table_primaryKey, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, clusteringKey, arginfo_class_Cassandra_Table_clusteringKey, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(Cassandra_Table, clusteringOrder, arginfo_class_Cassandra_Table_clusteringOrder, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_FE_END
};

static zend_class_entry *register_class_Cassandra_Table(void)
{
	zend_class_entry ce, *class_entry;

	INIT_NS_CLASS_ENTRY(ce, "Cassandra", "Table", class_Cassandra_Table_methods);
	class_entry = zend_register_internal_interface(&ce);

	return class_entry;
}
