#!/bin/bash

set -xe

declare -a PHP_VERSIONS=("8.5" "8.4" "8.3" "8.2")

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"

./scripts/compile-libuv.sh
./scripts/compile-cpp-driver.sh "scylladb"
./scripts/compile-cpp-driver.sh "datastax"

for version in "${PHP_VERSIONS[@]}"
do
    ./scripts/compile-php.sh -o "$PROJECT_ROOT/third-party/php" -v "$version" -s yes -d yes
done
