# First, find php-config if not already found
if (NOT PHP_CONFIG_FOUND)
    find_package(PHPConfig REQUIRED)
endif()

if (NOT PHP_CONFIG_FOUND)
    message(FATAL_ERROR "php-config is required")
endif ()

execute_process(COMMAND ${PHP_CONFIG_EXECUTABLE} --prefix OUTPUT_VARIABLE PHP_LIB_PREFIX OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${PHP_CONFIG_EXECUTABLE} --includes OUTPUT_VARIABLE PHP_INCLUDES_RAW OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${PHP_CONFIG_EXECUTABLE} --libs OUTPUT_VARIABLE PHP_LIBS OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${PHP_CONFIG_EXECUTABLE} --version OUTPUT_VARIABLE PHP_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${PHP_CONFIG_EXECUTABLE} --vernum OUTPUT_VARIABLE ZEND_API OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${PHP_CONFIG_EXECUTABLE} --extension-dir OUTPUT_VARIABLE PHP_EXTENSION_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${PHP_CONFIG_EXECUTABLE} --include-dir OUTPUT_VARIABLE PHP_INCLUDE_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${PHP_CONFIG_EXECUTABLE} --php-binary OUTPUT_VARIABLE PHP_EXECUTABLE OUTPUT_STRIP_TRAILING_WHITESPACE)

# Parse includes - php-config --includes returns "-I/path1 -I/path2 ..."
# We need to convert this to a CMake list of directories
string(REGEX REPLACE "-I" "" PHP_INCLUDES_CLEANED "${PHP_INCLUDES_RAW}")
string(REGEX REPLACE " +" ";" PHP_INCLUDE_DIRS "${PHP_INCLUDES_CLEANED}")
# Remove empty entries
list(REMOVE_ITEM PHP_INCLUDE_DIRS "")

# Also provide the raw includes string for backward compatibility
set(PHP_INCLUDES ${PHP_INCLUDE_DIRS})
message(STATUS "INCLUDES: ${PHP_INCLUDE_DIRS}")

# Get library directory
get_filename_component(PHP_LIB_DIR ${PHP_LIBS} DIRECTORY)

# Set all output variables
set(PHP_LDFLAGS "-L${PHP_LIB_DIR} ${PHP_LIBS}")
set(PHP_INCLUDE_DIRS ${PHP_INCLUDE_DIRS} CACHE STRING "PHP include directories")
set(PHP_INCLUDES ${PHP_INCLUDES})
set(PHP_VERSION ${PHP_VERSION})
set(ZEND_API ${ZEND_API})
set(PHP_EXTENSION_DIR ${PHP_EXTENSION_DIR})
set(PHP_INCLUDE_DIR ${PHP_INCLUDE_DIR})
set(PHP_EXECUTABLE ${PHP_EXECUTABLE})
set(PHP_FOUND ON)

mark_as_advanced(
    PHP_INCLUDE_DIRS
    PHP_INCLUDES
    PHP_VERSION
    PHP_EXECUTABLE
    PHP_EXTENSION_DIR
)

