find_package(PkgConfig REQUIRED)

if (USE_LIBCASSANDRA)
    if (PHP_DRIVER_STATIC)
        pkg_check_modules(LIBCASSANDRA REQUIRED IMPORTED_TARGET cassandra_static)
    else ()
        pkg_check_modules(LIBCASSANDRA REQUIRED IMPORTED_TARGET cassandra)
    endif ()

    target_link_libraries(ext_scylladb PRIVATE PkgConfig::LIBCASSANDRA)
    set(CASSANDRA_H "${LIBCASSANDRA_INCLUDE_DIRS}")
else ()
    if (PHP_DRIVER_STATIC)
        pkg_check_modules(LIBSCYLLADB REQUIRED IMPORTED_TARGET scylla-cpp-driver_static)
    else ()
        pkg_check_modules(LIBSCYLLADB REQUIRED IMPORTED_TARGET scylla-cpp-driver)
    endif ()

    target_link_libraries(ext_scylladb PRIVATE PkgConfig::LIBSCYLLADB)
    set(CASSANDRA_H "${LIBSCYLLADB_INCLUDE_DIRS}")
endif ()
