include(CheckIPOSupported)
include(CheckCXXCompilerFlag)
include(CheckCCompilerFlag)

function(target_optimize target native_arch)
    if (${CMAKE_BUILD_TYPE} MATCHES "Debug")
        target_compile_options(${target} PRIVATE -O0 -g3 -ggdb -gdwarf-4)
    endif ()

    if (${CMAKE_BUILD_TYPE} MATCHES "RelWithInfo")
        target_compile_options(${target} PRIVATE -O2 -g3 -ggdb -gdwarf-4)
    endif ()

    if (${CMAKE_BUILD_TYPE} MATCHES "Release")
        if (native_arch)
            check_cxx_compiler_flag(-march=native SUPPORT_MARCH_NATIVE)
            if (SUPPORT_MARCH_NATIVE)
                target_compile_options(${target} PRIVATE -march=native -O3)
            else ()
                message(WARNING "Compiler does not support `-march=native` required by PHP_SCYLLADB_OPTIMISE_FOR_CURRENT_MACHINE")
            endif ()
        endif ()
    endif ()
endfunction()