name: docker

on:
  workflow_call:
    inputs:
      upload_to_artifact:
        type: boolean
        default: false
        required: false
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/nano-interactive/cassandra-php-driver
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          submodules: recursive
      - name: Build LibUV
        run: make build-libuv
      - name: Build Cassandra CPP Driver
        run: make build-libcassandra
      - name: Builld Cassandra PHP Driver
        run: make build-cassandra-php-driver
      - name: Builld Cassandra PHP Driver
        run: make install
      - name: Run PHP Tests
        run: make php-test
      - uses: actions/upload-artifact@v2
        if: ${{ inputs.upload_to_artifact }}
        with:
          name: cassandra.so
          path: build-release/cassandra/Release/cassandra.so
