name: "Build Docker Image"

on:
  workflow_dispatch:
    inputs:
      php:
        description: "PHP Version"
        required: true
        default: '8.4'
      threading:
        type: string
        description: "nts or zts"
        required: true
        default: "nts"
      ubuntu_version:
        type: string
        description: 'Ubuntu Version'
        required: false
        default: '24.04'
      debug:
        type: string
        description: "PHP Debug -> Options [yes, no]"
        default: "no"
        required: false
  workflow_call:
    inputs:
      php:
        type: string
        description: "PHP Version"
        required: true
      debug:
        type: string
        description: "PHP Debug -> Options [yes, no]"
        required: false
      threading:
        type: string
        description: "nts or zts"
        required: true
      ubuntu_version:
        type: string
        description: "Ubuntu Version -> Options [22.04, 24.04]"
        required: false
        default: "24.04"
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-docker-image:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push API
        if: ${{ inputs.debug != 'yes' }}
        uses: docker/build-push-action@v5
        with:
          file: ./docker/Dockerfile
          context: .
          push: true
          pull: true
          platforms: linux/amd64/v3,linux/arm64/v8
          target: final
          tags: "malusevd99/scylladb-php-driver:ubuntu-${{ inputs.ubuntu_version }}-${{ inputs.php }}-${{ inputs.threading }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            UBUNTU_VERSION=${{ inputs.ubuntu_version }}
            PHP_VERSION=${{ inputs.php }}
            PHP_THREAD_MODEL=${{ inputs.threading }}
            PHP_DEBUG=no
            PHP_MEM_SANITIZERS=no
      - name: Build and push API
        if: ${{ inputs.debug == 'yes' }}
        uses: docker/build-push-action@v5
        with:
          file: ./docker/Dockerfile
          context: .
          push: true
          pull: true
          platforms: linux/amd64
          target: final
          tags: "malusevd99/scylladb-php-driver:ubuntu-${{ inputs.ubuntu_version }}-${{ inputs.php }}-${{ inputs.threading }}-debug"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            UBUNTU_VERSION=${{ inputs.ubuntu_version }}
            PHP_VERSION=${{ inputs.php }}
            PHP_THREAD_MODEL=${{ inputs.threading }}
            PHP_DEBUG=yes
            PHP_MEM_SANITIZERS=yes
