name: "Test PHP Extension"

on:
  workflow_call:
  push:
    branches:
      - v1.3.x
  pull_request:
    branches:
      - v1.3.x
jobs:
  test:
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
        threading: ['zts', 'nts']
        os: ['ubuntu-22.04', 'ubuntu-24.04']
        driver: ['scylladb', 'cassandra']
      fail-fast: false
    runs-on: ubuntu-24.04
    container: malusevd99/scylladb-php-driver:${{ matrix.os }}-${{ matrix.php }}-${{ matrix.threading }}-debug
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Cache Vendor
        uses: actions/cache@v3
        with:
          path: tests/vendor
          key: ${{ runner.os }}-${{ matrix.php }}-vendor-${{ hashFiles('**/composer.lock') }}

      - name: Build
        run: ./scripts/build.sh ${{ matrix.driver }}

      - name: Install PHP Dependencies
        working-directory: tests
        shell: bash
        run: |
          php -d extension=cassandra /php/bin/composer \
            --ignore-platform-reqs \
            --no-ansi \
            --prefer-dist \
            --no-interaction \
            --no-progress \
            install

      - name: Run tests
        working-directory: tests
        shell: bash
        run: |
          php -d extension=cassandra ./vendor/bin/pest \
          	--colors=always \
          	--fail-on-risky \
          	--fail-on-warning \
          	--fail-on-deprecation
